### ISSUE TITLE
amCalendar is broken

### ISSUE THREAD

**Issue by shahriar** [urish/ngx-moment#175]
amCalendar crashes the app. I am using angular2-moment like this. 

> message.created_at | amCalendar:{sameDay:'h:mm A', sameElse:'DD/MM/YYYY'} 
Last day I found this crashes the app with following stack trace. 

`ERROR TypeError: moment.isMoment is not a function
    at CalendarPipe.transform (calendar.pipe.js:39)
    at Object.eval [as updateRenderer] (ChatPage.ngfactory.js:347)
    at Object.updateRenderer (core.es5.js:12620)
    at checkAndUpdateView (core.es5.js:12149)
    at callViewAction (core.es5.js:12507)
    at execEmbeddedViewsAction (core.es5.js:12465)
    at checkAndUpdateView (core.es5.js:12145)
    at callViewAction (core.es5.js:12507)
    at execComponentViewsAction (core.es5.js:12439)
    at checkAndUpdateView (core.es5.js:12150)
`

**Environment:**

Please answer the following questions:

* Angular version? 4.1.3
* TypeScript version? 2.3.4
* `moment` version? 2.19.0
* Are you using `moment-timezone`? No
* Are you using the angular-cli? Yes
* Using Rollup/Webpack/System.js/Ionic/similar? Ionic

**Comment by blacksmith77** [comment]
moment 2.19.0 has breaking changes for angular2-moment
moment 2.18.1 is good.

**Comment by lonwi** [comment]
It works fine with latest moment 2.19.1 just in case
